### ISSUE TITLE
[Suggestion] Getting Started Pop-up

### ISSUE THREAD

**Issue by Philip-Clark** [Philip-Clark/IframeMultiViewer#1]
## Why?
It's confusing to launch a website only to be met with a blank screen. The Getting Started modal would walk users through the core functions, introduce shortcut commands, and provide links for help.

## What?
A show once modal that walks through the steps of adding/editing/deleting sources,  adding/editing/deleting tabs, shortcut reference, and a help link.

## Tasks

- [ ] Show once help Modal
- [ ] Pull from a Markdown file for the tutorial?
- [ ] Button to open help modal after shown once

## Additional things
- [How to display MarkDown in React](https://stackoverflow.com/a/31880296/17977603)
- [RemarkJS](https://github.com/remarkjs/react-markdown)
